version: 2.1

orbs:
  python: circleci/python@1.2
  node: circleci/node@4.7.0

workflows:
  build:
    jobs:
      - build-38

jobs:
  build-38:
    docker:
      - image: cimg/python:3.8
      - image: circleci/postgres:9.6.9-postgis
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    steps:
      - node/install
      - checkout
      - restore_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install -r requirements.txt --progress-bar off
            git submodule init
            git submodule update
            cp sms_site/circle_settings.py sms_site/local_settings.py
            python manage.py migrate
            python manage.py test
            pylint django_dialog_engine
            pylint django_dialog_engine_builder
            pylint quicksilver
            pylint simple_messaging
            pylint dashboard
            pylint simple_messaging_dialog_support
            bandit -r .
      - run:
          name: Test dialog content
          command: |
            . /home/circleci/venv/bin/activate
            cd ..
            cd django/dde
            npm install -g -s botium-cli botium-core
            export BOTIUM_DDE_DIALOG_SCRIPT_PATH="./django_dialog_engine/botium/dialog_scripts/hello_world.json"
            export BOTIUM_DDE_DIALOG_USER_ID="circle-ci:tester"
            export BOTIUM_DDE_DIALOG_ID="circle-ci-test-hello-world"
            botium-cli run -c django_dialog_engine/botium/botium.json -C django_dialog_engine/botium/convos/hello_world/
            export BOTIUM_DDE_DIALOG_SCRIPT_PATH="./django_dialog_engine/botium/dialog_scripts/prompt_test.json"
            botium-cli run -c django_dialog_engine/botium/botium.json -C django_dialog_engine/botium/convos/prompt_test/
      - save_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "/home/circleci/project/requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app
