# Generated by Django 3.2.25 on 2024-06-27 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1048576, unique=True)),
                ('country_code', models.CharField(max_length=1048576)),
                ('friendly_name', models.CharField(blank=True, max_length=1048576, null=True, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=4096, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=4096, null=True)),
                ('personalized_name', models.CharField(blank=True, max_length=4096, null=True)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='plan_safe.timezone')),
            ],
        ),
    ]
