# Generated by Django 3.2.25 on 2024-06-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1048576, unique=True)),
                ('identifier', models.CharField(max_length=1048576)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='study_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='plan_safe.studyarm'),
        ),
    ]
