# pylint: skip-file
# Generated by Django 3.2.25 on 2024-08-28 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0003_safetyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisHelpLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('voice_number', models.CharField(blank=True, max_length=1024, null=True)),
                ('messaging_number', models.CharField(blank=True, max_length=1024, null=True)),
                ('website', models.URLField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='coping_skills',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='environmental_safety',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='people_distraction',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='people_help',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='people_medical_provider',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='people_mental_health_provider',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='people_provider',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='warning_signs',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AlterField(
            model_name='safetyplan',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_plans', to='plan_safe.participant'),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=2048, null=True)),
                ('contact', models.CharField(blank=True, max_length=2048, null=True)),
                ('role', models.CharField(choices=[('distraction', 'Distraction'), ('help', 'Help'), ('medical', 'Medical Provider'), ('mental-health', 'Mental Heath Provider'), ('provider', 'Provider')], max_length=2048)),
                ('message', models.TextField(blank=True, max_length=1048576, null=True)),
                ('safety_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporters', to='plan_safe.safetyplan')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonForLiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('caption', models.TextField(blank=True, max_length=1048576, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plan_safe/reasons_images')),
                ('safety_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_for_living', to='plan_safe.safetyplan')),
            ],
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='crisis_help_lines',
            field=models.ManyToManyField(related_name='safety_plans', to='plan_safe.CrisisHelpLine'),
        ),
    ]
