# pylint: skip-file
# Generated by Django 3.2.25 on 2025-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0004_auto_20240828_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='login_token',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
