# pylint: skip-file
# Generated by Django 3.2.25 on 2025-01-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0005_participant_login_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crisishelpline',
            old_name='messaging_number',
            new_name='messaging_label',
        ),
        migrations.RenameField(
            model_name='crisishelpline',
            old_name='voice_number',
            new_name='messaging_url',
        ),
        migrations.AddField(
            model_name='crisishelpline',
            name='voice_label',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='crisishelpline',
            name='voice_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
