# pylint: skip-file
# Generated by Django 3.2.25 on 2025-02-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0006_auto_20250115_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisishelpline',
            name='order_label',
            field=models.IntegerField(default=0),
        ),
    ]
