# pylint: skip-file
# Generated by Django 3.2.25 on 2025-02-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0007_crisishelpline_order_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisishelpline',
            name='blurb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
