# pylint: skip-file
# Generated by Django 3.2.25 on 2025-03-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0008_crisishelpline_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyplan',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
