# pylint: skip-file
# Generated by Django 3.2.25 on 2025-04-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0009_safetyplan_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisishelpline',
            name='is_warmline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='message_distraction',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='message_help',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='message_medical_provider',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='safetyplan',
            name='message_mental_health_provider',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
    ]
