# pylint: skip-file
# Generated by Django 3.2.25 on 2025-09-19 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0010_auto_20250423_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='day_end',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='participant',
            name='day_start',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
