# pylint: skip-file
# Generated by Django 3.2.25 on 2025-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0011_auto_20250919_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
