# pylint: skip-file
# Generated by Django 5.2.14 on 2026-07-09 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_safe', '0012_alter_participant_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_created', models.DateTimeField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('warning_signs', models.TextField(blank=True, max_length=1048576, null=True)),
                ('coping_skills', models.TextField(blank=True, max_length=1048576, null=True)),
                ('environmental_safety', models.TextField(blank=True, max_length=1048576, null=True)),
                ('people_distraction', models.TextField(blank=True, max_length=1048576, null=True)),
                ('message_distraction', models.TextField(blank=True, max_length=8192, null=True)),
                ('people_help', models.TextField(blank=True, max_length=1048576, null=True)),
                ('message_help', models.TextField(blank=True, max_length=8192, null=True)),
                ('people_medical_provider', models.TextField(blank=True, max_length=1048576, null=True)),
                ('message_medical_provider', models.TextField(blank=True, max_length=8192, null=True)),
                ('people_mental_health_provider', models.TextField(blank=True, max_length=1048576, null=True)),
                ('message_mental_health_provider', models.TextField(blank=True, max_length=8192, null=True)),
                ('people_provider', models.TextField(blank=True, max_length=1048576, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('crisis_help_lines', models.ManyToManyField(related_name='safety_plans_versions', to='plan_safe.crisishelpline')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_plan_versions', to='plan_safe.participant')),
                ('safety_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='plan_safe.safetyplan')),
            ],
        ),
    ]
